### ISSUE TITLE
#bug isBefore operator gt instead of lt

### ISSUE THREAD

**Issue by rdhainaut** [rosostolato/odata-fluent-query#10]
### Bug description
In reviewing the code, I think i have found a typo mistake in the isBefore method (line 156) in create-filters.ts 
See: https://github.com/rosostolato/odata-fluent-query/blob/master/src/builders/create-filter.ts
![image](https://user-images.githubusercontent.com/19733832/107967937-0b545180-6fae-11eb-8796-60733b13ac68.png)

### Fix code
The code should be
```else return makeExp(`${key} lt ${d._key}`)```

**Comment by rosostolato** [comment]
Thank you! I pushed v2.1.1 with a fix for it.
