### ISSUE TITLE
#Feature #Bug Add an option to ignore implicite guid and process it as a normal string

### ISSUE THREAD

**Issue by rdhainaut** [rosostolato/odata-fluent-query#11]
### Description problem
I have an object on my model IProduct where userId is a 'string' type but has a GUID value.
I have not the full control on it because it s generates by a third library and the field is used as a 'string' type. 

When I try to use that field with the equals method available from FilterString interface your code handle it as a GUID and not as a string (see source section).
Code: 
```
ODataQuery<IProduct>.filter(p => p.userId.equals('123456-abcde-987654-zyxwvu')
// output $filter=userId eq 123456-abcde-987654-zyxwvu
// expected output $filter=userId eq '123456-abcde-987654-zyxwvu'
```

I encounter this error: 
```
"error": {
  "message": "The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand 
  types 'Edm.String' and 'Edm.Guid' for operator kind 'Equal'."
}
```

### Source
See: https://github.com/rosostolato/odata-fluent-query/blob/master/src/builders/create-filter.ts line 64
```
const equalityBuilder = (t: 'eq' | 'ne', x: any, opt?: StringOptions) => {
    switch (typeof x) {
      case 'string':
        if (isGuid.test(x)) {
          return makeExp(`${key} ${t} ${x}`) // no quote around ${x}
        }
```
        
### Solution / proposal

Add a parameter to stringOptions to explicite ignore GUID "implicite" value
or 
Add a parameter to stringOptions to explicite cast the value to GUID (but it is a breaking change)
or
...
### Workaround

I could use contains, startWidth or other string function to force the 'quote' in the query but it is more a hack than a good solution

**Comment by rosostolato** [comment]
Added `ignoreGuid` to `stringOptions` on version 2.2.0.

**Comment by rdhainaut** [comment]
Thanks a lot for your quick updated version.
