### ISSUE TITLE
#Feature Allow checking null for properties of object type and nullable ones

### ISSUE THREAD

**Issue by bhrytskiv** [rosostolato/odata-fluent-query#17]
### Description problem

`FilterBuilder` type doesn't have `equals` method signature, so there is no possibility to check if it's null or not. A similar problem with `equals` of other filter types except for `FilterString`. They can't accept null values when typescript is configured to strict mode.

Code:
```ts
interface Post {
    id: number;
    text: string;
    author: User;
    views: number | null;
}

// error on .equals(null), only User's properties can be called
odataQuery<Post>().filter(p => p.author.equals(null));

// error on null, when "strict" config in tsconfig.json is set to true
odataQuery<Post>().filter(p => p.views.equals(null));
```

### Solution / proposal

Add `equals` and `notEquals` methods to `FilterBuilder` type
or
Add `FilterObject` type that has `equals` and `notEquals` methods
or
...

Add `null` to union type of parameter of `equals` and `notEquals` methods of filter types
or
Check nullability of `T` in `FilterBuilderType<T>` as well
or
...

### Workaround

It's working by using type casting `FilterBuilder` to `any` and `null` to appropriate type through casting to `unknown` type.

Code:
```ts
// output $filter=author eq null
odataQuery<Post>().filter(p => (p.author as any).equals(null));

// output $filter=views eq null
odataQuery<Post>().filter(p => p.views.equals(null as unknown as number));
```

**Comment by rosostolato** [comment]
@bhrytskiv can you please share your `tsconfig.json` file?

**Comment by bhrytskiv** [comment]
@rosostolato sure
```json
{
    "compileOnSave": false,
    "compilerOptions": {
      "strictPropertyInitialization": false,
      "baseUrl": "./",
      "outDir": "./dist/out-tsc",
      "sourceMap": true,
      "declaration": false,
      "downlevelIteration": true,
      "experimentalDecorators": true,
      "moduleResolution": "node",
      "importHelpers": true,
      "strict": true,
      "target": "es2015",
      "module": "es2020",
      "lib": [
        "es2018",
        "dom"
      ]
    },
    "angularCompilerOptions": {
      "enableI18nLegacyMessageIdFormat": false
    }
}
```

This configs are used in angular v11 application, typescript v4.1.5

**Comment by rosostolato** [comment]
I tried to infer `null` type but had no success so I added a second overload for all method that compares values to be able to add `null` or `undefined`.

**Comment by rosostolato** [comment]
pushed v2.5.0 containing the fix.

**Comment by bhrytskiv** [comment]
@rosostolato very cool!
And what about null checking for object type properties?

**Comment by rosostolato** [comment]
@bhrytskiv humm.... you're right. For that, I think I'll just add `isNull`and `notNull` because it doesn't make sense to compare the whole object.

**Comment by rosostolato** [comment]
@bhrytskiv do you think that `isNull` and `notNull` only can solve the first issue you had? To compare against `null` you will always need to use those methods like this:

```ts
interface Post {
    id: number;
    text: string;
    author: User;
    views: number | null;
}

// expected error
odataQuery<Post>().filter(p => p.author.isNull()); // <- won't work here because `author` is not nullable

// working as intended
odataQuery<Post>().filter(p => p.views.isNull());
```

**Comment by bhrytskiv** [comment]
@rosostolato looks pretty good, that's totally what I'm looking for
p. s. `author` in example should have been nullable, sorry for my mistake

**Comment by rosostolato** [comment]
@bhrytskiv I have dropped the `null | undefined` overload and added the `FilterNullable` methods that add `isNull` and `notNull` for all filter types, including objects, arrays, Date, and more. PR https://github.com/rosostolato/odata-fluent-query/pull/19

**Comment by bhrytskiv** [comment]
Thanks a lot for your work and quick updates

**Comment by rdhainaut** [comment]
@rosostolato Thanks for this new feature that handles properly the nullable "case" <3 
Now I use > the v.2.5.1 I can't stop to explicitely cast the field ... My code is nicer :) 💯
