### ISSUE TITLE
#Feature odata-v4 Built-in Query Functions support e.g. concat

### ISSUE THREAD

**Issue by darkflame0** [rosostolato/odata-fluent-query#20]
http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html

especially concat,it's frequently used.

**Comment by rosostolato** [comment]
Thank for opening this issue. I've been busy lately, but I'll try to work on it asap. If you feel confortable to create a pull request, it will help a lot.

**Comment by rosostolato** [comment]
published v2.6.1
