### ISSUE TITLE
odata-fluent-query@2.6.1/node_modules/odata-fluent-query/dist/builders/create-groupby.js 27:33 Module parse failed: Unexpected token (27:33)

### ISSUE THREAD

**Issue by nanivijay** [rosostolato/odata-fluent-query#25]
I am running in to below issue in my project after updating the package to 2.6.1
Could you please help what is the reason ad how to fix this?

odata-fluent-query@2.6.1/node_modules/odata-fluent-query/dist/builders/create-groupby.js 27:33
Module parse failed: Unexpected token (27:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return (keys, aggregate) => {
|         const agg = groupbyBuilder();
>         const result = aggregate?.(agg) || agg;
|         return createQuery({
|             ...descriptor,

**Comment by nanivijay** [comment]
In our existing project we are using optional chaining. let me try to repro this on a sample project.
<img width="252" alt="image" src="https://github.com/rosostolato/odata-fluent-query/assets/5945591/c841f528-74a1-4d32-82d8-e30c36af2e88">

**Comment by nanivijay** [comment]
Not able to repro on code sandbox sample. https://codesandbox.io/s/fast-dream-dlc5kq?file=/src/App.tsx

**Comment by rosostolato** [comment]
Yeah, it works there! It's hard to say what's going on. I would try to update the webpack package or even try to migrate to Vite.

**Comment by nanivijay** [comment]
We are using `webpack 4` and Babel `babel-loader`. The optional chaining operator works in `webpack 5`. Looks like babel or webpack not able to prase the optional chaining operator

**Comment by rosostolato** [comment]
That makes sense. You can either update to webpack 5 if it's possible or you can build this repository to an old javascript version, es6 or even es5. I'm closing this issue for now.
