### ISSUE TITLE
Filtering using Guid

### ISSUE THREAD

**Issue by hig0r** [rosostolato/odata-fluent-query#3]
Because I treat guid as strings, odata-fluent-query adds single quotes around it: `$filter=entityId%20eq%20%27003b63b4-e0b0-40db-8d5f-fb388bf0eabc%27`, which causes the following error in my api:

> The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'.

maybe the filter method should verify if the string is a guid and not add single quotes around it?
```
case 'string':
if (/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x)) { // is a Guid?
  return mk_exp(`${this.prefix} eq ${x}`); // no quote around ${x}
}
```

**Comment by rosostolato** [comment]
Thank you for the report. I believe that your solution might work, I will implement it

**Comment by rosostolato** [comment]
Please, try version 1.1.3

**Comment by hig0r** [comment]
**It's working**
thanks!
