### ISSUE TITLE
[Build] Broken build from V2.7.0 (vite compatibility)

### ISSUE THREAD

**Issue by rdhainaut** [rosostolato/odata-fluent-query#30]
I use odata-fluent-query in a vue 3 project (with a dependency to vite v4.5.0) .
With the previous version (v2.6.1) no problem but when i try to update to new version (v.2.7.0) i have this error message

[plugin:vite:import-analysis] Failed to resolve entry for package "odata-fluent-query". The package may have incorrect main/module/exports specified in its package.json.

**Comment by rosostolato** [comment]
I guess I found the issue. Please, try again with v2.7.3

**Comment by rdhainaut** [comment]
I have just tested locally with v2.7.3 and now it works as expected (no error message) :) !
Thanks for the quick fix.

**Comment by rosostolato** [comment]
Great! Thanks
