### ISSUE TITLE
Adding OData Aggregation extension to use $apply

### ISSUE THREAD

**Issue by cjhaviland** [rosostolato/odata-fluent-query#5]
Looking to get the OData Aggregation Extension v4.0](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html) added in per the v4 specs. Currently I don't see anyway to use the aggregation or at least write a custom query string.

Thanks.

**Comment by cjhaviland** [comment]
JK just found the GroupBy method...

**Comment by rosostolato** [comment]
Cool! This feature is kind experimental, I just used once. So if you find any issue or any suggestion, please be free to share.

**Comment by cjhaviland** [comment]
@rosostolato I take it back. I am trying to do something like: `?$apply=filter(DescriptionYear eq '2020')/groupby((Description))` but I don't believe that's possible. It might be better to have an `apply` method rather than just the `groupBy`? Or maybe a way to write custom filter strings within the ODataQuery.

**Comment by rosostolato** [comment]
Can't you just do?
```ts
odataQuery<MyData>()
  .filter(q => q.DescriptionYear.inTimeSpan(2020))
  .groupBy('Description')
```

**Comment by cjhaviland** [comment]
@rosostolato I did end up getting something to work. That property is actually a string so this worked:

```ts
odataQuery<MyData>()
  .filter((q) => q.descriptionYear.equals('2020'))
      .groupBy(['description'])
```

Which created this query string: `$filter=descriptionYear eq '2019'&$apply=groupby((description, descriptionYear))`

Since my API is built with EF Core I think there will be a few limitations, but at least this worked! Thanks for the tip. I just have a little more information in my return data than expected.

**Comment by rosostolato** [comment]
Cool... Yeah I forgot it was an array, I'm glad it worked.

Do you suggest any changes, like an `apply` method? What would be the parameters?
