### ISSUE TITLE
#Question Optional fields in SelectExpression (strict mode)

### ISSUE THREAD

**Issue by rdhainaut** [rosostolato/odata-fluent-query#6]
### Error Description
I have a compilation error when I use the arrow function with select odata-fluent-query function when a field from my model is optional.

### Sample

```
interface MyData {
id: number;
firstname: string;
middlename?: string;
lastname: string;
}

const queryExample = odataQuery<MyData>()
      .select(
        x => x.firstname, 
        x => x.middlename, // this line triggers an error (see below)
        x=> x.lastname
      ).toString();
```

```
Argument of type '(x: SelectBuilder<MyData>) => SelectExpression | undefined' is not assignable to parameter of type '((exp: SelectBuilder<MyData>) => SelectExpression) | "id" | "firstname" | "middlename" | "lastname"'.
  Type '(x: SelectBuilder<MyData>) => SelectExpression | undefined' is not assignable to type '(exp: SelectBuilder<MyData>) => SelectExpression'.
    Type 'SelectExpression | undefined' is not assignable to type 'SelectExpression'.
      Type 'undefined' is not assignable to type 'SelectExpression'.ts(2345)
```

### Workaround
I can cast explicitely the SelectExpression to `x => x.middlename as string`

### Question
Do you think is it possible to handle the undefined without explicit casting ?

Maybe you could change the type of SelectParams to `export declare type SelectParams<T, Tkey> = Array<Tkey | ((exp: SelectBuilder<T>) => SelectExpression | undefined)>;` (in other words add a pipe undefined) in query-select.d.ts to handle that case (but it could have other side effect ?) ? 

### Note
I have found this library few days ago and i use it to refactoring my odata query.
I appreciate this strong type syntax. Thanks for your work.

 I love the arrow function syntax and the huge benefits is the support for refactoring/renaming in IDE 👍

**Comment by rosostolato** [comment]
Yes... I think so. We can assert the types, I haven't done it before because I didn't care about strict mode. But I will look at it and probably fix these 3 bugs you reported. Thank you!

**Comment by rosostolato** [comment]
I've just pushed version 2.1.0 with a fix for it. Please check if it works now.
