### ISSUE TITLE
#Bug Multi orderBy with identical prop key on the root object is not supported (latest win)

### ISSUE THREAD

**Issue by rdhainaut** [rosostolato/odata-fluent-query#8]
### Error Description
Multi orderBy clauses on the root object with the same prop key is not supported
The correct behavior should merge them with coma separated values
The actual behavior overwrite previous orderby value(s)

### Example
```
odataQuery<IBook>
 .orderBy(p => p.Category.Name.desc())
 .orderBy(p => p.Author.Name.desc())
```
 
should produce
`$orderby=Category/Name desc, Author/Name desc`

and not 
`$orderby=Author/Name desc`

**Comment by rosostolato** [comment]
Hey there! Thank you for your reporting... I will take a time to look deep into them and will get back soon

**Comment by rosostolato** [comment]
I've just pushed version 2.1.0 with a fix for it. Please check if it works now.

**Comment by rdhainaut** [comment]
It works perfectly now :) Good job and Thank you
